language: ruby
cache: bundler
rvm:
  - 2.4.0
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'create database SlowFoodApril_test;' -U postgres
script:
  - bundle exec rails ci:tests
